### ISSUE TITLE
Is there any way to get a PHSScene Preview?

### ISSUE THREAD

**Issue by aaronn** [PhilipsHue/HueSDK#10]
Is there any way to get a PHSScene preview, either in the form of possible LightStates (ideally) or an image? The PHSScene has a 'picture', but it's an NSString and doesn't seem to return anything.

**Comment by jhvdb87** [comment]
A PHSScene object contains a list of lights. From those lights you can get the light state (light.lightState). However, you first have to call fetch on the scene object. Fetch retrieves the light states for the lights, of that scene, from the bridge.

The 'picture' field is just a placeholder to store a unique id that links to an image in your app.

**Comment by aaronn** [comment]
@jhvdb87 this isn’t the scene’s lightstate though, it’s the lightstate of the light right? I’m trying to populate a list of scenes and want to get the colors or photo a scene will be using while the lights are not yet in that lightstate so users have a preview instead of just the name

**Comment by jhvdb87** [comment]
If you do a fetch on the scene, the light point will contain the light state that belongs to the scene

**Comment by aaronn** [comment]
Interesting @jhvdb87 . This returns null for every result on my end. Any ideas?

>     NSArray *rawSceneArray = [[_bridge bridgeState] getBridgeResourcesOfType:PHSDomainTypeScene];
>     _sceneArray = [[NSMutableArray alloc] init];
>     
>     for (PHSScene* scene in rawSceneArray) {
>         PHSScene *fetchedScene = (PHSScene*)[[_bridge bridgeState] getBridgeResourceOfType:PHSDomainTypeScene withIdentifier:scene.identifier];
>         NSLog(@"%@", ((PHSLightPoint*)fetchedScene.lights.firstObject).lightState.color);
>     }
>

**Comment by aaronn** [comment]
@jhvdb87 Ah I see what I was missing now– there's literally a `[scene fetchWithAllowedConnections:...]` call. Thanks!
