### ISSUE TITLE
Native library (libhuesdk.so) for armv7 (32 bit)

### ISSUE THREAD

**Issue by LarsK93** [PhilipsHue/HueSDK#12]
Dear Developer-Team,
Would it be possible that you provide the native library file (libhuesdk.so) for armv7 32 bit architecture?
That would make life much easier as it would be possible to run HueSDK on Raspberry Pi for example.
Thanks in advance!

**Comment by jhvdb87** [comment]
I put the request on our backlog. I'll keep you posted when this will be picked up.

**Comment by JensTimmerman** [comment]
Even better would be to publish the source code for libhuesdk? So we can compile it for our platform?

**Comment by mrwhy-orig** [comment]
@jhvdb87 And the armv7 build?

**Comment by jhvdb87** [comment]
We are currently picking up this ticket. It requires specific version of stdc++, so would you rather distribute a static library as mentioned in https://github.com/PhilipsHue/HueSDK/issues/19. 
Is that Ok for you ?

**Comment by mrwhy-orig** [comment]
@jhvdb87 yeah, that would be Ok for me. Do you have a road map for this?

**Comment by jhvdb87** [comment]
Release with this will probably happen in the next 2 months. Not on this repo, because this one is going to be deprecated. 
Link to subscribe: https://developers.meethue.com/content/edk-terms-use

**Comment by mrwhy-orig** [comment]
@jhvdb87, looking forward to that. Hope i would be sooner.

**Comment by jhvdb87** [comment]
We are a bit delayed with the release unfortunately. The aim is end of August.

**Comment by jhvdb87** [comment]
Libraries with statically linked stdc++ are available on our new repo.
