### ISSUE TITLE
No Entertainment in SDK?

### ISSUE THREAD

**Issue by aalleexxx5** [PhilipsHue/HueSDK#16]
I'm following some of the steps of the "[Entertainment Programming via Hue SDK](https://developers.meethue.com/documentation/entertainment-programming-hue-sdk)" guide on the meethue page. Which went fine for a couple of minutes, until I had to use the Entertainment object.

It appears this is not included in the SDK and the EDK page on GitHub leads to a 404.
Did I miss something, or have you yet to include the entertainment features in the SDK?

-Ps:
(context: I wanted to quickly fire up an already-created entertainment area, so I skipped all the steps of light and area setup, to just use what I have created through the hue app.)

**Comment by Tuikku** [comment]
I think you need to fill out [this form](https://developers.meethue.com/documentation/getting-started-development-hue-entertainment) to get access to EDK.

**Comment by jhvdb87** [comment]
Indeed you need to fill in the form mentioned by @Tuikku. 
After filling in the form we will grant you access as soon as possible.
