### ISSUE TITLE
Remote connection at iOS

### ISSUE THREAD

**Issue by rchampa** [PhilipsHue/HueSDK#18]
I have the following swift code:

    func buildBridge(info:PHBridgeInfo) -> PHSBridge {

        // Replace app name and device name
        return PHSBridge.init(block: { (builder) in
            builder?.connectionTypes = .remote
            let device = UIDevice.current
            let uid = device.identifierForVendor?.uuidString
            builder?.setupRemote(withAppID: "myapp", withDeviceID: "es.ricardo.com", withAccountGUID: nil, withcallbackURL: "https://localhost", withclientID: "client", withClientSecret: "secret")            

            builder?.bridgeConnectionObserver = self
            builder?.add(self)

        }, withAppName: "MyApp", withDeviceName: "MyDevice")

    }

 
    let bridgeInfo:PHBridgeInfo

    lazy var bridge:PHSBridge = {

        let b = buildBridge(info:bridgeInfo)
        let brc = b.getConnection(PHSBridgeConnectionType.remote) as! PHSRemoteBridgeConnection

        //this line is not working, url is always an empty string ""
        let url = brc.getLoginURL()
        return b
    }()

While in Android the equivalent code is fully working.

    bridge = new BridgeBuilder("myapp", Build.MODEL)
        .setConnectionType(BridgeConnectionType.REMOTE)
        .setupRemote(appid, Build.DEVICE, null, "https://localhost", clientid, clientsecret)
        .setBridgeConnectionCallback(bridgeConnectionCallback)
        .addBridgeStateUpdatedCallback(bridgeStateUpdatedCallback)
        .build();
    String url = ((RemoteBridgeConnection)bridge.getBridgeConnection(BridgeConnectionType.REMOTE)).getLoginURL();
    Log.d(TAG,"URL -> " + url);
    webview.loadUrl(url);
 

Any explanation why brc.getLoginURL() is not working properly at iOS ?

**Comment by jhvdb87** [comment]
You are using nil values in the bridge setupRemote method, which results in nil from getLoginURL().
