### ISSUE TITLE
iOS version doesn't build.

### ISSUE THREAD

**Issue by NeoTeo** [PhilipsHue/HueSDK#2]
Xcode 9.0 (9A235), macOS 10.13 (17A405)
The build ends with errors running the shell script 'Run Script'

```
rm: /Users/teo/source/Apple/iOS/Hue/HueSDK/HueQuickStartApps/HueQuickStartApp-iOS/Dependencies/HueSDK/phone/active/HueSDK.framework: No such file or directory
ln: /Users/teo/source/Apple/iOS/Hue/HueSDK/HueQuickStartApps/HueQuickStartApp-iOS/Dependencies/HueSDK/phone/active/HueSDK.framework: No such file or directory
```

When in fact the framework is in 
`/Users/teo/source/Apple/iOS/Hue/HueSDK/HueQuickStartApps/HueQuickStartApp-iOS/Dependencies/HueSDK/phone/device/HueSDK.framework`
and
`/Users/teo/source/Apple/iOS/Hue/HueSDK/HueQuickStartApps/HueQuickStartApp-iOS/Dependencies/HueSDK/phone/simulator/HueSDK.framework`

**Comment by Tuikku** [comment]
Build fails because it tries to delete file that is not there.
You can add force flag to rm command to make it work.

`rm -Rf "${BASE_DIR}/active/HueSDK.framework"`

**Comment by Tuikku** [comment]
Created pull request with better way to handle it #3
