### ISSUE TITLE
[Documentation] Add Java Desktop HowTo

### ISSUE THREAD

**Issue by mrwhy-orig** [PhilipsHue/HueSDK#22]
At the moment i'm stuck at getting a desktop app running. A guide to kickstart a Java Desktop app would be nice. Should I use the new SDK for desktop apps, or should i use the old one?
Also I don't understand why there is a native lib linked. What is the native lib doing?

**Comment by jhvdb87** [comment]
For which platform are you developing ? 
The native lib is required, because it contains the core functionality of the SDK which is written in C++.

**Comment by mrwhy-orig** [comment]
Windows (Tests/Dev), Linux on ARM(Production)
