### ISSUE TITLE
Android SDK Remote api tutorial

### ISSUE THREAD

**Issue by tpapagiannis** [PhilipsHue/HueSDK#29]
Hi, i would like to tell me how to use android sdk for using the Remote API.
I would like to send me a tutorial code for this.
I have declared an app, i have the clientid, client secret etc.
Thanks.

**Comment by jeroenbeuz** [comment]
I would like to get this as well.

**Comment by tpapagiannis** [comment]
I use the following to setup remote access and pass Username that I took from the Oauth2 process:

Newbridge = new BridgeBuilder("LyfeShieldWellAgeing", android.os.Build.MODEL)
        //  .setIpAddress(bridgeIp)
        .setConnectionType(BridgeConnectionType.REMOTE)
        .setBridgeConnectionCallback(bridgeConnectionCallback)
        .addBridgeStateUpdatedCallback(bridgeStateUpdatedCallback)

        .setupRemote("lyfeshieldwellageing", Build.DEVICE, null, "lyfeshieldapp://huecallback",
                ClientID,  ClientSecret)
         .setUserName(Username)
        .build();

   Newbridge.connect();


It does not connect and it gives me the error:

E/HueSDK: PortalConnectionErrorParser: got fault, remote connection error: 0
04-17 13:26:17.577 31878-32395/com.smarts.lyfeshieldwellageing E/HueSDK: PortalConnectionErrorParser: got http code 0


 Connection event: LOGIN_REQUIRED
04-18 15:05:35.793 17093-19028/com.smarts.lyfeshieldwellageing I/Praeda: Connection event: COULD_NOT_CONNECT

If i use this code: 

 // set access_token
        OAuthTokenPair tokenPair= new OAuthTokenPair();
        tokenPair.setAccessToken(prefs.getAccess_Token());
        tokenPair.setRefreshToken(prefs.getRefresh_Token());
        connection.setAccessTokens(tokenPair);

then it tell me : NO_BRIDGE_FOR_PORTAL_ACCOUNT.


WHAT IS THE PROBLEM WITH MY CODE ?

PLEASE HELP.

**Comment by tpapagiannis** [comment]
No answer from Philips for days !!!!
Mercy please, i have 6 days loosing my time searching why Remote Acceess does not work.
I have follow all guidelines, but docs are not full so detailed as always from Philips.

**Comment by jeroenbeuz** [comment]
Its been almost 3 weeks now. This is ridiculous..

**Comment by jhvdb87** [comment]
@jeroenbeuz There is no official documentation on the remote API yet. For now you can use the example above.
If you encounter a similar issue (NO_BRIDGE_FOR_PORTAL_ACCOUNT) as mentioned by @tpapagiannis, please send an email to philipshuedev@philips.com. They will reconfigure your remote API account.

**Comment by jeroenbeuz** [comment]
@jhvdb87 Ok I will try that. Thanks.
