### ISSUE TITLE
Any plans to update this HueSDK?

### ISSUE THREAD

**Issue by vmorris1959** [PhilipsHue/HueSDK#32]
There haven't been any update to the actual SDK in 8 months!
If this is not under development let us know so we developers don't waste our time building apps with it.

**Comment by jhvdb87** [comment]
New versions of the (beta) HueSDK will be released on our other channel. On that channel we released SDK with entertainment support recently. 
Link to subscribe: https://developers.meethue.com/content/edk-terms-use

This repository will be deprecated soon.
