### ISSUE TITLE
Scene Transition Times returning null after a bridge reconnect

### ISSUE THREAD

**Issue by danzada1** [PhilipsHue/HueSDK#34]
My code is able to successfully retrieve the transition time of a newly created scene if my app does not reconnect to the bridge. But after a reconnect, I only receive null when calling getTransitionTime on a fetched scene, even though the light states are retrieved OK. Any ideas on how to fix?

Thanks!

**Comment by jhvdb87** [comment]
Transition time is a write only value and not part of the JSON on retrieval from the bridge. That's why the value is null.
I would rather use the transition time on the light states you set for the lights in the scene.

**Comment by danzada1** [comment]
Thanks! That makes sense and is working for me now.
