### ISSUE TITLE
Sensor.getIdentifier() returning incorrect value for Motion Sensor ID

### ISSUE THREAD

**Issue by danzada1** [PhilipsHue/HueSDK#35]
Hi again, the new java API is returning "00:17:88:01:02:01:33:f1" as the Sensor ID of a Motion Sensor on my Bridge network using:

`Sensor.getIdentifier()`

The old Java API shows ID: "44" for this same sensor. The new API returns the IDs of all the other types of sensor in the correct "##" format, not sure why the Motion Sensor is different. Deleting and re-finding the Motion Sensor does not change this predicament.

I can't use "00:17:88:01:02:01:33:f1" for any API calls.

Thanks!

**Comment by jhvdb87** [comment]
The motion sensor is a compound sensor, an object that only exists on SDK level. On bridge level the motion sensor are three individual sensors; grouping is done by SDK. As id we use the mac address of the sensor and indeed you can not perform operations on the compound sensor. If you want to update any of the sensors, you are able to get the sensors from the compound sensor and update them individually.

**Comment by danzada1** [comment]
Thanks for the quick reply!

> If you want to update any of the sensors, you are able to get the sensors from the compound sensor and update them individually.

How would I go about doing that with this SDK? Could you give a brief code example? It is not obvious to me after quite a bit of playing with the Sensor object.

Thanks!

**Comment by jhvdb87** [comment]
CompoundSensor (which inherits from CompoundDevice) has method to get list of devices. The device can be casted to a sensor or you directly perform the operation on the device by calling update_state/update_configuration

**Comment by danzada1** [comment]
Ah that makes sense, thanks!
