### ISSUE TITLE
Android Studio Emulators (and some users) can't find Bridge during bridge search

### ISSUE THREAD

**Issue by danzada1** [PhilipsHue/HueSDK#37]
I also have some App users who are unable to find their bridge after updating to the newest version of my app which switched from the old SDK to this new one. I'm using the below code from the Quick start app.

`bridgeDiscovery = new BridgeDiscovery();
bridgeDiscovery.search(BridgeDiscovery.BridgeDiscoveryOption.ALL, bridgeDiscoveryCallback);`

Thanks!

**Comment by danzada1** [comment]
Update: I've updated to the newest EDK 1.23.1.5 version. Using the 

`BridgeDiscovery.BridgeDiscoveryOption.ALL`

 search function, one of the bridges on my network is found but the other is not. However the pushlink authentication is not working in my App or in the Quickstart App that was provided.

**Comment by danzada1** [comment]
Update2: Still using the Android Emulator and it is working about 1/4th of the time. Now I'm frequently receiving this error in the Log:

`E/HueSDK: Retriever: invalid json retrieved from: http://192.168.1.69/api/ycnDdig99etkx-JMynWUcRPsM0zmCVrRtiCKPYi7, resource path: `

**Comment by danzada1** [comment]
Update3: There are still users of my application who are unable to find their bridge with the 1.23.1.5 SDK version. I will have to revert back to the old SDK if this is not resolved shortly, however I was told that my App would need to be using this new SDK by June 2018 so I'm somewhat confused at the moment. The old SDK was working fine in Android Studio and I had zero reports of not being able to find bridges.

Thanks for your help!

**Comment by jhvdb87** [comment]
Can you enable debug logging and attach it to this ticket ? 
Can you open the ticket next time in the new repo ? https://github.com/PhilipsHue/HueSDK4EDK
This repository is going to be deprecated

**Comment by danzada1** [comment]
Yes will re-open in the new repo, thanks!
