### ISSUE TITLE
Offline Support on Restricted Network

### ISSUE THREAD

**Issue by mharikumarna** [PhilipsHue/HueSDK#39]
I'm having an iPad that is connected to the same n/w switch (via Ethernet adapter) as the bridge. The philips hue app is able to control the lights. Will I be able to create an iOS app that can control the lights in a similar way? 
ps: This is on corporate network and the bridge doesn't have connection to the internet.

**Comment by jhvdb87** [comment]
Yes you can. Please check our sample iOS app for inspiration :)
