### ISSUE TITLE
Offline availability of resources

### ISSUE THREAD

**Issue by jeroenbeuz** [PhilipsHue/HueSDK#4]
So I'm busy implementing the new SDK. Looking very good so far! Great work. I would like to know if it's possible to retrieve objects like bridges and groups when you're not connected. So are these objects persisted upon connection with a bridge, to be retrieved later on when no connection is possible?

I would like to know this because I would like my users to be able to see the bridges and groups they have connected with, even when they have no connection to the bridge. If not, I would have to create my own models and save them, but I have the feeling the SDK already persists them on disk.

Keep up the great work!

**Comment by jhvdb87** [comment]
The SDK persists the resources on disk. Therefore you have to set a storage location on the SDK as mentioned in our documentation. 
We have a concept called "KnownBridges" (KnownBridges in Java, PHSKnownBridges in ObjC). You can get all the bridges you've ever been connected to. The returned objects contains the bridge identifier and can be used to construct a new bridge object with the bridge builder. When the bridge identifier is injected in the bridge by the bridge builder, the SDK will load all the resources automatically from persistence. You can access the resources through the bridge state (bridge.getBridgestate() in Java and bridge.bridgeState in ObjC).

**Comment by jeroenbeuz** [comment]
Thanks! Works great.
