### ISSUE TITLE
Access point/token in Bridge info

### ISSUE THREAD

**Issue by Natashfine** [PhilipsHue/HueSDK#40]
Hello,
I am working with both Hue libraries for iOS and Android, 
At the Android library there is object AccessPoint which owns a token that helps me know if that bridge already been found once and been connected to.
I cannot find anything like this in the iOS app.
Is there anything like this in the framework?

Many thanks,
Natasha

**Comment by jhvdb87** [comment]
There is no such thing as an access point in our Java wrapper on this library.
Are you using https://github.com/PhilipsHue/PhilipsHueSDK-Java-MultiPlatform-Android ? Support and the libraries are deprecated

**Comment by Natashfine** [comment]
Thank you @jhvdb87,
The problem is in the iOS library, not Android.
Anyway I overcame this problem using rest api provided by PhilipsHue.
