### ISSUE TITLE
New light not detected.

### ISSUE THREAD

**Issue by ashokKOMARA** [PhilipsHue/HueSDK#41]
SDK is not detecting light when i change my old light to new one in ---> self.bridgeController?.bridge.bridgeState.getDevicesOf(.light) this method, even after i reset the hue, I don't know why. Is there any method to detect new lights.
Thanks in advance.

**Comment by jhvdb87** [comment]
Yes there is a method in PHSBridge: findNewDevices

**Comment by ashokKOMARA** [comment]
Thanks for your replay, but i didn't find any method like that in gitHub downloaded SDK(iOS). but i can able to find it in android SDK. Can you please provide me a sample code for it to get new lights in iOS SDK.
