### ISSUE TITLE
Unable to run the quickstart app in Steve Hue Emulator

### ISSUE THREAD

**Issue by sagar3235** [PhilipsHue/HueSDK#42]
I am using Andriod QuickStart app and trying to connect to Steve Hue Emulator.
I have installed the android app in my device and Steve Emulator in my PC which are connected to the same network.
But when I am calling the Bridge.Connect() method my application is getting crash and there is no call back to check the error.
Can anyone help me to solve this issue.

Thanks in advance.
reply asap.

**Comment by jhvdb87** [comment]
The Steve Hue Emulator is not officially supported by us. It could be that the responses returned by the emulator cause this crash in the SDK. Could you send us the full SDK logs to philipshuedev@philips.com so we can analyse this issue.
