### ISSUE TITLE
Developer registration not working

### ISSUE THREAD

**Issue by DarkoDamjanovic** [PhilipsHue/HueSDK#43]
Hello,

It is not possible to create a developer account here:
https://developers.meethue.com/content/edk-terms-use

After typing in all my data like name, etc..  pressing the "Register" button just reloads the page. (tried on two different MacBooks with Chrome and Safari) Support is only possible after you log in, but I can't log in because I can't register for an account. It's this chicken-or-egg problem...

Also the other mentioned URL is dead:
https://github.com/PhilipsHue/HueSDK4EDK/

We just want the latest Mobile SDK's.

Please advice. Thanks.

**Comment by jhvdb87** [comment]
Please contact philipshuedev@philips.com

**Comment by EricRabil** [comment]
Could you guys update the README so it isn't as misinforming? All links for the new project are dead.
