### ISSUE TITLE
QuickStartAppSwift is missing directory check in build script

### ISSUE THREAD

**Issue by doschi** [PhilipsHue/HueSDK#5]
The swift example App does not work out of the box.
The run script build phase is missing the check if the "active" framework directory already exists.

  if [ -d "${BASE_DIR}/active/" ]
  then
  rm -R "${BASE_DIR}/active/HueSDK.framework"
  else
  mkdir "${BASE_DIR}/active/"
  fi

**Comment by jhvdb87** [comment]
The run script was indeed missing for the swift target. The problem should be fixed.
