### ISSUE TITLE
Bridge specifications ?

### ISSUE THREAD

**Issue by elistone** [PhilipsHue/HueSDK#6]
Does this SDK work with any version of hue bridge?

**Comment by jhvdb87** [comment]
It should work with all v1 and v2 bridges.
Did you encounter any issue ?

**Comment by elistone** [comment]
I did have a problem searching for a v2 bridge, was getting bridge not found - when using the demo app & after creating it myself.

I then ran updates on my bridge and it started to work.
It did again start not finding bridges but seemed a bit intermittent (with it more likely to find), with changing the `PHSBridgeDiscoveryOption` method an easy fix.

Feel free to close this ticket, as I don't believe it to be an issue - at least not one that cannot be solved by updating the bridge or changing the discovery option.
