### ISSUE TITLE
Bridge null in onBridgeStateUpdated

### ISSUE THREAD

**Issue by jeroenbeuz** [PhilipsHue/HueSDK#8]
Sometimes, upon connecting to a bridge, the bridge inside the BridgeStateUpdatedCallback is null. It looks to me that this should not happen. This callback is meant to indicate a bridge has a new state, so therefore the bridge should not be null. I'm currently catching when this occurs, my method looks like this:

`/**
     * The callback the receives bridge state update events
     */
    private BridgeStateUpdatedCallback bridgeStateUpdatedCallback = new BridgeStateUpdatedCallback() {
        @Override
        public void onBridgeStateUpdated(Bridge bridge, BridgeStateUpdatedEvent bridgeStateUpdatedEvent) {
            Log.i(TAG, "Bridge state updated event: " + bridgeStateUpdatedEvent);
            if (bridge == null) {
                Log.d(TAG, "BRIDGE IS NULL!");
                new DebugNotification(BridgeService.this).showDebugNotification("Bridge is null!", "In bridgeStateUpdatedCallback", 50);
                return;
            }
}`

It only happens when I start my app and it connects to a bridge.

**Comment by jhvdb87** [comment]
It should not happen indeed. We will investigate the cause.

**Comment by jeroenbeuz** [comment]
Any updates on this?

**Comment by jhvdb87** [comment]
No, there is no update yet on this issue

**Comment by jhvdb87** [comment]
I am not able to reproduce the problem. Can you elaborate more on the scenario to reproduce this ?

**Comment by jeroenbeuz** [comment]
Have not seen this issue anymore. Probably due to bridge update.
