### ISSUE TITLE
How to use BridgeBuilder.setupRemote()

### ISSUE THREAD

**Issue by jeroenbeuz** [PhilipsHue/HueSDK#9]
Can't seem to find any documentation for this. Can you please explain how to setup remote connection to a bridge?

**Comment by jhvdb87** [comment]
The remote connection is currently only available for a selected group of partners and developers. We are working on this to get it available for everyone. If you are interested, you could already signup to get access to our remote API:  https://developers.meethue.com/content/remote-api (no guarantees if it will be granted for the time being).
The documentation will be updated as soon as the remote connection is available for everyone.
